### ISSUE TITLE
Does Not Work in VS 2022 Blazor App Net6.0

### ISSUE THREAD

**Issue by TorreyGarland** [surgicalcoder/RazorPageRouteGenerator#1]
Please take a look at Andrew Lock's article at [https://andrewlock.net/using-source-generators-with-blazor-in-dotnet-6/](url).  There is an issue with source generators not being able to read code generated by other source generators.  He opened an issue, but as far as I can tell it has not been resolved yet.

please let me know if I missed something.

Cheers!

**Comment by surgicalcoder** [comment]
Hi @TorreyGarland 

Are you using it with WebAssembly or Blazor Server?

The [example in the repos](https://github.com/surgicalcoder/RazorPageRouteGenerator/tree/master/GoLive.Generator.RazorPageRoute.Tests.BlazorWebAsssembly) works for me in both VS22 and JetBrains Rider,

Have you got a project you can share?

**Comment by TorreyGarland** [comment]
using Blazor Server with the latest update of VS 2022 Community Edition

**Comment by surgicalcoder** [comment]
Hi @TorreyGarland 

It seems like the only solution (until you can chain source generators) is to disable Razor Source Code Generation, and go back to the two stage build process,

You need to put  `<UseRazorSourceGenerator>false</UseRazorSourceGenerator>` inside a PropertyGroup to do that

Sorry!
